networks:
  pg_network:
    driver: bridge
services:
  bank:
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4000M
        reservations:
          cpus: '4'
          memory: 4000M
    environment:
      ALGORITHM: GOROUTINE
      DB_HOST: postgres
      DELAY_TRANSACTION: '0.09999999999999999'
      INTERFACE_TYPE: PGX
      MAX_CONNECTIONS: 80
      NUMBER_OF_ACCOUNTS: '1000'
      NUMBER_OF_TRANSACTIONS: '100000'
    image: bank-go
    networks:
    - pg_network
    volumes:
    - ./bankData:/app/bankData
  postgres:
    container_name: postgres
    deploy:
      resources:
        limits:
          cpus: '3'
        reservations:
          cpus: '3'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
    healthcheck:
      interval: 10s
      retries: 5
      test: pg_isready -h postgres
      timeout: 5s
    image: postgres:latest
    networks:
    - pg_network
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
version: '3.8'
volumes:
  postgres_data: null
